// Regenerates per-operation MDX stubs in content/docs/reference/ from openapi.yaml.
// Usage: node scripts/generate-openapi.mjs
//
// `<APIPage>` is registered globally via mdx-components.tsx, so generated MDX
// can reference it without an import.
//
// The script wipes every generated subdirectory under
// `content/docs/reference/` (one per OpenAPI tag) before writing so that paths
// or tags removed from `openapi.yaml` don't leave orphaned MDX files behind —
// orphans break `next build` because Next tries to prerender pages whose
// `<APIPage>` references a path no longer present in the spec. The
// hand-authored `index.mdx` is preserved, and the root `meta.json` is
// regenerated by the `beforeWrite` hook below — keep HAND_AUTHORED_PAGES and
// REFERENCE_META in sync with the files on disk.
//
// `content/docs/reference` is a *root folder* (`"root": true`), which is what
// makes it the second layout tab next to Documentation. The `beforeWrite` hook
// must keep emitting that flag — dropping it silently deletes the tab at the
// next build. CLI and MCP live under `content/docs/(guide)/usage/`, in the
// Documentation tab, and are generated by scripts/generate-cli.mjs.

import { readdirSync, rmSync, readFileSync } from "node:fs";
import { join } from "node:path";

import { generateFiles } from "fumadocs-openapi";
import { createOpenAPI } from "fumadocs-openapi/server";

import { chooseSpecSource } from "../lib/docs-sync/spec-source.mjs";
import { normalizeSpec } from "../lib/docs-sync/normalize-spec.mjs";

const OUTPUT_DIR = "./content/docs/reference";

// The document id that generated MDX references via `<APIPage document=... />`.
// It must match the input key used at runtime in lib/openapi.ts so the client
// component can look the spec up in the preloaded map.
const DOCUMENT_ID = "./openapi.yaml";

// Hand-authored top-level pages (without extension), in nav order. They sit
// above the generated API groups.
const HAND_AUTHORED_PAGES = ["index"];

// Static part of the section meta. `root: true` promotes Reference to a layout
// tab; the title is what the tab is labelled with.
const REFERENCE_META = {
  title: "API Reference",
  icon: "Library",
  root: true,
  collapsible: false,
};

// Subdirectories this script must NOT wipe. Everything under reference/ is
// generated per OpenAPI tag now that cli/ has moved to (guide)/usage/cli.
const PRESERVED_DIRS = new Set();

// Wipe generated subdirectories (one per tag). Keep `index.mdx` and any
// other hand-authored top-level files — the only top-level write the
// generator does is `meta.json`, regenerated unconditionally.
for (const entry of readdirSync(OUTPUT_DIR, { withFileTypes: true })) {
  if (entry.isDirectory() && !PRESERVED_DIRS.has(entry.name)) {
    rmSync(join(OUTPUT_DIR, entry.name), { recursive: true, force: true });
  }
}

const spec = chooseSpecSource(process.env);
let rawSpec;
if (spec.kind === "url") {
  const res = await fetch(spec.value, { headers: { "User-Agent": "bitrouter-docs-openapi" } });
  if (!res.ok) throw new Error(`OpenAPI fetch ${res.status} from ${spec.value}`);
  rawSpec = await res.text();
  console.log(`generate-openapi: fetched spec from ${spec.value}`);
} else {
  rawSpec = readFileSync(spec.value, "utf8");
}
// Hoist nested `$defs` to the document root so fumadocs-openapi v11's ref
// parser can resolve the spec's root-absolute `#/$defs/...` pointers.
const document = normalizeSpec(rawSpec);
const openapi = createOpenAPI({ input: { [DOCUMENT_ID]: document } });

await generateFiles({
  input: openapi,
  output: OUTPUT_DIR,
  per: "operation",
  groupBy: "tag",
  includeDescription: true,
  meta: { folderStyle: "folder" },
  beforeWrite(files) {
    // Write the API Reference section meta — a root folder, i.e. its own
    // layout tab. generateFiles writes the file at "meta.json" relative to the
    // output dir.
    const root = files.find((f) => f.path === "meta.json");
    if (!root) return;
    const meta = JSON.parse(root.content);
    // Hand-authored pages first (index lands the section at /docs/reference,
    // and is what the tab links to), then the generated Cloud API groups.
    const pages = [...HAND_AUTHORED_PAGES, "---Cloud API---", ...(meta.pages ?? [])];
    root.content = JSON.stringify({ ...REFERENCE_META, pages }, null, 2) + "\n";
  },
});

console.log("Generated API Reference MDX from openapi.yaml");
