// Regenerates per-operation MDX stubs in content/docs/reference/ from openapi.yaml.
// Usage: node scripts/generate-openapi.mjs
//
// `<APIPage>` is registered globally via mdx-components.tsx, so generated MDX
// can reference it without an import.
//
// The script wipes every generated subdirectory under
// `content/docs/reference/` (one per OpenAPI tag) before writing so that paths
// or tags removed from `openapi.yaml` don't leave orphaned MDX files behind —
// orphans break `next build` because Next tries to prerender pages whose
// `<APIPage>` references a path no longer present in the spec. The
// hand-authored `index.mdx` is preserved, and the root `meta.json` is
// regenerated by the `beforeWrite` hook below.

import { readdirSync, rmSync, readFileSync } from "node:fs";
import { join } from "node:path";

import { generateFiles } from "fumadocs-openapi";
import { createOpenAPI } from "fumadocs-openapi/server";

import { chooseSpecSource } from "../lib/docs-sync/spec-source.mjs";
import { normalizeSpec } from "../lib/docs-sync/normalize-spec.mjs";

const OUTPUT_DIR = "./content/docs/reference";

// The document id that generated MDX references via `<APIPage document=... />`.
// It must match the input key used at runtime in lib/openapi.ts so the client
// component can look the spec up in the preloaded map.
const DOCUMENT_ID = "./openapi.yaml";

// Wipe generated subdirectories (one per tag). Keep `index.mdx` and any
// other hand-authored top-level files — the only top-level write the
// generator does is `meta.json`, regenerated unconditionally.
for (const entry of readdirSync(OUTPUT_DIR, { withFileTypes: true })) {
  if (entry.isDirectory()) {
    rmSync(join(OUTPUT_DIR, entry.name), { recursive: true, force: true });
  }
}

const spec = chooseSpecSource(process.env);
let rawSpec;
if (spec.kind === "url") {
  const res = await fetch(spec.value, { headers: { "User-Agent": "bitrouter-docs-openapi" } });
  if (!res.ok) throw new Error(`OpenAPI fetch ${res.status} from ${spec.value}`);
  rawSpec = await res.text();
  console.log(`generate-openapi: fetched spec from ${spec.value}`);
} else {
  rawSpec = readFileSync(spec.value, "utf8");
}
// Hoist nested `$defs` to the document root so fumadocs-openapi v11's ref
// parser can resolve the spec's root-absolute `#/$defs/...` pointers.
const document = normalizeSpec(rawSpec);
const openapi = createOpenAPI({ input: { [DOCUMENT_ID]: document } });

await generateFiles({
  input: openapi,
  output: OUTPUT_DIR,
  per: "operation",
  groupBy: "tag",
  includeDescription: true,
  meta: { folderStyle: "folder" },
  beforeWrite(files) {
    // Write the API References section meta (collapsible folder, not a tab).
    // generateFiles writes the file at "meta.json" relative to the output dir.
    const root = files.find((f) => f.path === "meta.json");
    if (!root) return;
    const meta = JSON.parse(root.content);
    // Prepend the hand-authored landing page so the section has a route at /docs/reference.
    const pages = ["index", ...(meta.pages ?? [])];
    root.content = JSON.stringify(
      { title: "API References", icon: "Library", defaultOpen: false, pages },
      null,
      2,
    ) + "\n";
  },
});

console.log("Generated API Reference MDX from openapi.yaml");
